#ifndef HMAKE_TARGETTYPE_HPP
#define HMAKE_TARGETTYPE_HPP

enum class TargetType : uint8_t
{
    EXECUTABLE,
    LIBRARY_STATIC,
    LIBRARY_SHARED,
    PLIBRARY_STATIC,
    PLIBRARY_SHARED,
};

#endif // HMAKE_TARGETTYPE_HPP
