#!/usr/bin/env python3
"""Scan decentralized UE HMake files and generate the root hmake.cpp."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

IGNORED_DIRECTORIES = {".git", "Binaries", "Build", "Intermediate", "Saved"}
ENUM_TYPES = {
    "platform": "UePlatform",
    "architecture": "UeArchitecture",
    "buildConfiguration": "UeBuildConfiguration",
    "targetType": "UeTargetType",
}
COMMAND_FIELDS = (
    "cppCompileCommand",
    "cCompileCommand",
    "linkCommand",
    "linkDependenciesPrefix",
    "linkCommandSuffix",
    "archiveCommand",
)


def default_ue_root() -> Path:
    current = Path.cwd().resolve()
    if (current / "Engine" / "Source").is_dir():
        return current

    sibling = Path(__file__).resolve().parents[3] / "UnrealEngine"
    return sibling if (sibling / "Engine" / "Source").is_dir() else current


def scan(ue_root: Path) -> list[Path]:
    files: list[Path] = []
    for file in ue_root.rglob("*.hmake.hpp"):
        relative_parts = file.relative_to(ue_root).parts
        if any(part in IGNORED_DIRECTORIES for part in relative_parts):
            continue
        files.append(file.resolve())

    files.sort(key=lambda file: file.as_posix())
    return files


def load_build_commands(file: Path) -> list[dict[str, str]]:
    rows = json.loads(file.read_text(encoding="utf-8"))
    if not isinstance(rows, list) or not rows:
        raise ValueError(f"Build-command table must be a non-empty JSON array: {file}")

    required = set(ENUM_TYPES) | set(COMMAND_FIELDS)
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            raise ValueError(f"Build-command row {index} is not an object: {file}")
        missing = required - row.keys()
        if missing:
            raise ValueError(f"Build-command row {index} is missing {sorted(missing)}: {file}")
    return rows


def cpp_string(value: str) -> str:
    return json.dumps(value)


def cpp_raw_string(value: str) -> str:
    delimiter = "HMAKE_UE_COMMAND"
    if f"){delimiter}\"" in value:
        raise ValueError("Command contains the generated C++ raw-string delimiter")
    return f'R"{delimiter}({value}){delimiter}"'


def generate(files: list[Path], commands: list[dict[str, str]], ue_root: Path) -> str:
    generated_include_root = (
        ue_root / "Engine" / "Intermediate" / "Build" / "Linux" / "UnrealServer" / "Inc"
    ).as_posix()
    lines = [
        "// Generated by Projects/UE5/scanner.py. Do not edit.",
        '#include "Configure.hpp"',
        "",
        "namespace",
        "{",
    ]

    for index, file in enumerate(files):
        lines.extend(
            [
                f"namespace ue_generated_file_{index}",
                "{",
                f"#include {cpp_string(file.as_posix())}",
                "}",
                "",
            ]
        )

    lines.extend(
        [
            "constexpr UeIncludedFile generatedUeFiles[] =",
            "{",
        ]
    )
    for index, file in enumerate(files):
        lines.append(
            f"    {{{cpp_string(file.as_posix())}, ue_generated_file_{index}::specify}},"
        )
    lines.extend(
        [
            "};",
            "",
            "// Bootstrap command rows obtained from a successful local UBT invocation:",
            "//     make UnrealServer-Linux-Debug",
            "// cppCompileCommand comes from the local UBT HMake export's BASE-COMMAND and maps",
            "// to the shared CppCompileEnvironment/toolchain prefix. HMake removes UBT's -c",
            "// because CppSrc appends -c, dependency, source, and -o arguments per file.",
            "// cCompileCommand uses the equivalent flags from UBT's MiMalloc.c response file.",
            "// linkCommand is the",
            "// UnrealServer-Linux-Debug.link.rsp prefix through -o, and archiveCommand maps to",
            "// UBT's UE-SDK llvm-ar invocation.",
            "//",
            "// Engine/Source is appended as the target-wide default include root. This maps to",
            "// UBT's default include-path setup and supports includes beginning with Runtime/,",
            "// Developer/, Editor/, and Programs/ without exposing an HMake-only module API.",
            "//",
            "// Generated C++ follows UEBuildModuleCPP: HMake scans handwritten sources for",
            "// UE_INLINE_GENERATED_CPP_BY_NAME(Name), leaves those includes active, and compiles",
            "// only the remaining UHT *.gen.cpp files (including *.init.gen.cpp) separately.",
            "const UeBuildCommandEntry generatedUeBuildCommands[] =",
            "{",
        ]
    )
    default_source_include = f' -I"{(ue_root / "Engine" / "Source").as_posix()}" '
    obsolete_generated_cpp_switch = '-D"HMAKE_COMPILE_GENERATED_CPP_SEPARATELY=1" '
    for row in commands:
        cpp_compile_command = row["cppCompileCommand"].replace(obsolete_generated_cpp_switch, "") + default_source_include
        c_compile_command = row["cCompileCommand"].replace(obsolete_generated_cpp_switch, "") + default_source_include
        lines.extend(
            [
                "    {",
                f"        .platform = UePlatform::{row['platform']},",
                f"        .architecture = UeArchitecture::{row['architecture']},",
                f"        .buildConfiguration = UeBuildConfiguration::{row['buildConfiguration']},",
                f"        .targetType = UeTargetType::{row['targetType']},",
                "        .commands =",
                "        {",
                f"            .cppCompileCommand = {cpp_raw_string(cpp_compile_command)},",
                f"            .cCompileCommand = {cpp_raw_string(c_compile_command)},",
                f"            .linkCommand = {cpp_raw_string(row['linkCommand'])},",
                f"            .linkDependenciesPrefix = {cpp_raw_string(row['linkDependenciesPrefix'])},",
                f"            .linkCommandSuffix = {cpp_raw_string(row['linkCommandSuffix'])},",
                f"            .archiveCommand = {cpp_raw_string(row['archiveCommand'])},",
                "        },",
                "    },",
            ]
        )
    lines.extend(
        [
            "};",
            "} // namespace",
            "",
            "void configurationSpecification(Configuration &baseConfiguration)",
            "{",
            "    auto &configuration = static_cast<UeConfiguration &>(baseConfiguration);",
            "    configuration.configureRequestedTargets();",
            "}",
            "",
            "void buildSpecification()",
            "{",
            "    // A full non-unity UnrealServer build can otherwise exhaust Linux memory.",
            "    cache.numberOfBuildProcesses = 16;",
            "",
            "    registerGeneratedUeSpecifyFuncs(generatedUeFiles);",
            "",
            '    UeConfiguration &configuration = getUeConfiguration("UnrealServerLinuxDebug");',
            "    configuration",
            "        .setPlatform(UePlatform::Linux, {UePlatformGroup::Unix, UePlatformGroup::Desktop, UePlatformGroup::Linux})",
            "        .setArchitecture(UeArchitecture::x64)",
            "        .setBuildConfiguration(UeBuildConfiguration::Debug)",
            "        .setUeTargetType(UeTargetType::Server)",
            "        .setBuildCommands(generatedUeBuildCommands)",
            "        .setGeneratedIncludeRoot(Node::getHalfNodeNonNormalized(",
            f"            {cpp_string(generated_include_root)}))",
            '        .requestTarget("UnrealServer");',
            "    // UBT's compile command already selects the bundled libc++ headers. Do not",
            "    // add HMake's host standard-library target (which would leak /usr/include).",
            "    configuration.assign(ConfigType::DEBUG, TargetType::LIBRARY_STATIC, IsCppMod::NO,",
            "                         AssignStandardCppTarget::NO);",
            "",
            "    CALL_CONFIGURATION_SPECIFICATION",
            "}",
            "",
            "MAIN_FUNCTION",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hmake.cpp from decentralized UE *.hmake.hpp files."
    )
    parser.add_argument(
        "--ue-root",
        type=Path,
        default=default_ue_root(),
        help="Unreal Engine checkout root (default: current UE checkout or sibling UnrealEngine directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Generated C++ file (default: <ue-root>/hmake.cpp).",
    )
    parser.add_argument(
        "--commands",
        type=Path,
        default=Path(__file__).with_name("build_commands.json"),
        help="JSON command table (default: Projects/UE5/build_commands.json).",
    )
    args = parser.parse_args()

    ue_root = args.ue_root.expanduser().resolve()
    if not (ue_root / "Engine" / "Source").is_dir():
        parser.error(f"UE root does not contain Engine/Source: {ue_root}")

    output = args.output.expanduser().resolve() if args.output else ue_root / "hmake.cpp"
    command_file = args.commands.expanduser().resolve()
    files = scan(ue_root)
    commands = load_build_commands(command_file)
    generated = generate(files, commands, ue_root)

    previous = output.read_text(encoding="utf-8") if output.exists() else None
    if previous == generated:
        print(f"Unchanged: {output} ({len(files)} files, {len(commands)} command rows)")
        return

    output.write_text(generated, encoding="utf-8")
    print(f"Generated: {output} ({len(files)} files, {len(commands)} command rows)")


if __name__ == "__main__":
    main()
